docker
docker login
docker build -t imagename:tag(v1) .
docker push imagename:tag
docker images(show the image list)
docker ps(container list)
docker ps -a (list of all container)
docker rm containerid(delete the conatiner)
docker rmi imageid(delete the docker image)
docker run imagename(run the conatiner)
docker logs containerid
docker exec -it containername bash(exce:exectuable it:interactive terminal)
